#!/bin/bash

parentdir=$(dirname $(readlink -f $0))

dnsconvert_bin="$parentdir/dnsconvert.py"

# filename of the input file in the repo
dnsinput="dnsinput"

# directory were static output files are found
staticdir="/tmp/dnsmanual"

# directory were to put output files
confdir="/tmp/dnsout"

# filename prefix of output files
dnsoutput="dnsoutput"

