#!/bin/bash

# git hook to call conversion utility after a push, to convert & deploy pushed contents
# source: http://codeutopia.net/blog/2011/06/30/how-to-automatically-run-unit-tests-from-a-git-push/

parentdir=$(dirname $(readlink -f $0))
source "$parentdir/hookconfig"

while read oldrev newrev refname
do
    # Only run this script for the master branch. You can remove this
    # if block if you wish to run it for others as well.
    if [[ $refname = "refs/heads/master" ]] ; then

        echo "Deploying $newrev ... "

        # Since the repo is bare, we need to put the actual files someplace,
        # so we use the temp dir we chose earlier
        git archive $newrev | tar -x -C "$confdir" -f - "$dnsinput"

    fi
done
 
exit 0
